### ISSUE TITLE
Tutorial question

### ISSUE THREAD

**Issue by vishiri** [tomsoderlund/nextjs-express-mongoose-crudify-boilerplate#2]
Hello,

This is probably going to be a really stupid question, but I am a beginner with this type of tech and I have been trying to get your template to work and the only thing I got stuck on is this part"

> export MONGODB_URI=*your mongodb url* // you can get one for free at https://www.mlab.com/home

Where EXACTLY am I supposed to put this line of code (with the proper URL ofc)? Some file? Terminal? Or where?

Thanks ahead for the answer.

**Comment by rmar72** [comment]
Importing it to your server file will do.

**Comment by tomsoderlund** [comment]
@Elvanos Sorry for late reply, were you able to solve it?
